name: Opencost repo

on:
 push:
   branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
       - "go get -d ./..."
       - "go mod vendor"
    - name: Test 
      run: go test  -v ./...
