name: Develop PR - build, test

on:
  pull_request:
    branches:
      - develop

jobs:
  build-with-cost-model-develop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: ./kubecost/cost-model

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./kubecost/cost-model
          file: ./kubecost/cost-model/Dockerfile
          push: false
